# Generated by Django 5.1.1 on 2024-11-02 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHeroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('vida', models.CharField(max_length=5)),
                ('ataque', models.CharField(max_length=5)),
                ('defensa', models.CharField(max_length=5)),
                ('fechasalida', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/miweb/')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoheroe')),
            ],
        ),
    ]
