# Generated by Django 5.1.1 on 2026-05-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expense_category_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Presupuesto mensual en pesos', max_digits=12),
        ),
    ]
