# Generated by Django 5.1.1 on 2026-05-15 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_budget_monthly_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre de la meta (ej: Comprar PC Gamer)', max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Cantidad objetivo a ahorrar', max_digits=12)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad ahorrada hasta ahora', max_digits=12)),
                ('deadline', models.DateField(blank=True, help_text='Fecha límite opcional para cumplir la meta', null=True)),
                ('emoji', models.CharField(default='🎯', help_text='Emoji representativo de la meta', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
