# Generated by Django 5.1.1 on 2026-05-25 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_savinggoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='next_occurrence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('', 'No recurrente'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_instances', to='core.expense'),
        ),
    ]
